---
title: "Mouse liver Bar Graphs and Heatmaps"
author: "John Santiago"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
library(rgl)
knitr::opts_chunk$set(echo = FALSE, fig.align="center")
knitr::knit_hooks$set(webgl = hook_webgl)

```

```{r include=F}

library(edgeR)
library(plot3D)
library(heatmaply)
library(gplots)
library(org.Mm.eg.db)

##ensembl = useMart("ensembl",dataset="hsapiens_gene_ensembl")
##ID.conversion=getBM(attributes=c("ensembl_gene_id","external_gene_name"),mart=ensembl)

```


##EdgeR comparisons
```{r include=F}
lcounts=read.csv("https://raw.githubusercontent.com/SashaBurgess/Mouse-Muscle-Liver-Data-/master/Liver_CountData.csv",row.names=1,header=T)

lgroups=read.csv("https://raw.githubusercontent.com/SashaBurgess/Mouse-Muscle-Liver-Data-/master/Mouse_Liver_Metadata.csv",row.names=1,header=T)

mcounts=read.csv("https://raw.githubusercontent.com/SashaBurgess/Mouse-Muscle-Liver-Data-/master/Muscle_CountData.csv",row.names=1,header=T)

mgroups=read.csv("https://raw.githubusercontent.com/SashaBurgess/Mouse-Muscle-Liver-Data-/master/Mouse_Muscle_Metadata.csv",row.names=1,header=T)

x <- lcounts[,row.names(lgroups)]
group <- factor(lgroups$Group)
y <- DGEList(counts=x,group=group)
keep <- filterByExpr(y)
y <- y[keep,,keep.lib.sizes=FALSE] 
z <- calcNormFactors(y, method = "TMM") 
lz=z
lcpmdata=cpm(z,base=2)

design<-model.matrix(~0+group)
colnames(design) <- levels(group)
z = estimateGLMCommonDisp(z,design, verbose=T)
z = estimateGLMTrendedDisp(z,design)
z = estimateGLMTagwiseDisp(z,design)
fit <- glmFit(z, design)


##C2 vs C1
compare = makeContrasts(C2-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
C2=G_X_E$table
sC2=C2[C2$FDR<.05,]

##C3 vs C1
compare = makeContrasts(C3-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
C3=G_X_E$table
sC3=C3[C3$FDR<.05,]

##C4 vs C1
compare = makeContrasts(C4-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
C4=G_X_E$table
sC4=C4[C4$FDR<.05,]

##C5 vs C1
compare = makeContrasts(C5-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
C5=G_X_E$table
sC5=C5[C5$FDR<.05,]

###

##R2 vs C1
compare = makeContrasts(R2-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
R2=G_X_E$table
sR2=R2[R2$FDR<.05,]

##R3 vs C1
compare = makeContrasts(R3-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
R3=G_X_E$table
sR3=R3[R3$FDR<.05,]

##R4 vs C1
compare = makeContrasts(R4-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
R4=G_X_E$table
sR4=R4[R4$FDR<.05,]


##R5 vs C1
compare = makeContrasts(R5-C1, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
R5=G_X_E$table
sR5=R5[R5$FDR<.05,]

##R2 vs C2
compare = makeContrasts(R2-C2, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
RC2=G_X_E$table
sRC2=RC2[RC2$FDR<.05,]

##R3 vs C3
compare = makeContrasts(R3-C3, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
RC3=G_X_E$table
sRC3=RC3[RC3$FDR<.05,]

##R4 vs C4
compare = makeContrasts(R4-C4, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
RC4=G_X_E$table
sRC4=RC4[RC4$FDR<.05,]

##R4 vs C4
compare = makeContrasts(R5-C5, levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
RC5=G_X_E$table
sRC5=RC5[RC5$FDR<.05,]

lcpmdata=read.csv("https://raw.githubusercontent.com/SashaBurgess/Mouse-Muscle-Liver-Data-/master/Liver_CPM_Data.csv",row.names=1)

lmeancpm=read.csv("https://raw.githubusercontent.com/SashaBurgess/Mouse-Muscle-Liver-Data-/master/Mean_Liver_CPM_Data.csv",row.names=1)

x <- mcounts[,row.names(mgroups)]
group <- factor(mgroups$Group)
y <- DGEList(counts=x,group=group)
keep <- filterByExpr(y)
y <- y[keep,,keep.lib.sizes=FALSE] 
z <- calcNormFactors(y, method = "TMM") 
mz=z
mcpmdata=cpm(mz,base=2)

```

##PCA Contribution Plot
```{r}
pca <- prcomp(t(lcpmdata), scale.=TRUE) 
gr <- factor(lgroups$Group)

xcoords=pca$x[,1]
ycoords=pca$x[,2]


eigs <- pca$sdev^2
ve=(eigs / sum(eigs))*100
ve=signif(ve,3)

barplot(height=ve)

```

##PCA PC1 vs PC2
```{r , fig.align="center",fig.height=10,fig.width=10}

pcacolors=c("gold","royalblue3","red4")
text2D(x=xcoords,y=ycoords,labels = c(rep("",27)), 
       col=c(pcacolors[c(rep(1,3),rep(1,12),rep(2,12))]),
       xlab=paste("PC1 (",ve[1],"%)",sep=""),ylab=paste("PC2 (",ve[3],"%)",sep=""),main="Liver Samples")

lines2D(x=xcoords[lgroups$Replicate==1&lgroups$Treat=="Control"],
        y=ycoords[lgroups$Replicate==1&lgroups$Treat=="Control"],
        col=pcacolors[2],add=T,lty=1)

lines2D(x=xcoords[lgroups$Replicate==2&lgroups$Treat=="Control"],
        y=ycoords[lgroups$Replicate==2&lgroups$Treat=="Control"],
        col=pcacolors[2],add=T,lty=2)

lines2D(x=xcoords[lgroups$Replicate==3&lgroups$Treat=="Control"],
        y=ycoords[lgroups$Replicate==3&lgroups$Treat=="Control"],
        col=pcacolors[2],add=T,lty=3)

lines2D(x=xcoords[((lgroups$Group=="C1"&lgroups$Replicate==1)+(lgroups$Replicate==1&lgroups$Treat=="Rapa"))==1],
        y=ycoords[((lgroups$Group=="C1"&lgroups$Replicate==1)+(lgroups$Replicate==1&lgroups$Treat=="Rapa"))==1],
        col=pcacolors[3],add=T,lty=1)

lines2D(x=xcoords[((lgroups$Group=="C1"&lgroups$Replicate==2)+(lgroups$Replicate==2&lgroups$Treat=="Rapa"))==1],
        y=ycoords[((lgroups$Group=="C1"&lgroups$Replicate==2)+(lgroups$Replicate==2&lgroups$Treat=="Rapa"))==1],
        col=pcacolors[3],add=T,lty=2)

lines2D(x=xcoords[((lgroups$Group=="C1"&lgroups$Replicate==3)+(lgroups$Replicate==3&lgroups$Treat=="Rapa"))==1],
        y=ycoords[((lgroups$Group=="C1"&lgroups$Replicate==3)+(lgroups$Replicate==3&lgroups$Treat=="Rapa"))==1],
        col=pcacolors[3],add=T,lty=3)

text2D(x=xcoords[gr=="C1"],y=ycoords[gr=="C1"],labels=c(rep("0H",3)),colkey=F,col="black",add=T,cex=1)

text2D(x=xcoords[gr=="C2"],y=ycoords[gr=="C2"],labels=c(rep("30min",3)),col="royalblue3",add=T,cex=1)
text2D(x=xcoords[gr=="C3"],y=ycoords[gr=="C3"],labels=c(rep("1H",3)),col="royalblue3",add=T,cex=1)
text2D(x=xcoords[gr=="C4"],y=ycoords[gr=="C4"],labels=c(rep("2H",3)),col="royalblue3",add=T,cex=1)
text2D(x=xcoords[gr=="C5"],y=ycoords[gr=="C5"],labels=c(rep("4H",3)),col="royalblue3",add=T,cex=1)

text2D(x=xcoords[gr=="R2"],y=ycoords[gr=="R2"],labels=c(rep("30min",3)),col="red3",add=T,cex=1)
text2D(x=xcoords[gr=="R3"],y=ycoords[gr=="R3"],labels=c(rep("1H",3)),col="red3",add=T,cex=1)
text2D(x=xcoords[gr=="R4"],y=ycoords[gr=="R4"],labels=c(rep("2H",3)),col="red3",add=T,cex=1)
text2D(x=xcoords[gr=="R5"],y=ycoords[gr=="R5"],labels=c(rep("4H",3)),col="red3",add=T,cex=1)

abline(h=0,lty=2)
abline(v=0,lty=2)

legend("topleft", legend=c("Control","Rapamycin"),col=c("royalblue3","red3"),lty=1,bty="n",lwd=2)
```

##Total DEG in Timecourse Barplot
```{r}

barplot(height=c(nrow(sC2),nrow(sC3),nrow(sC4),nrow(sC5),NA,nrow(sR2),nrow(sR3),nrow(sR4),nrow(sR5)),col=c(rep("royalblue",4),NA,rep("red3",4)),names.arg = c(".5HC","1HC","2HC","4HC","",".5HR","1HR","2HR","4HR"),ylab="Total Sig. DEG",main="Liver Relative to Fasted",ylim=c(0,2500))

```

##Total DEG Between Timecourse Barplot
```{r}

barplot(height=c(nrow(sRC2),nrow(sRC3),nrow(sRC4),nrow(sRC5)),col="mediumpurple3",names.arg = c(".5H R/C","1H R/C","2H R/C","4H R/C"),ylab="Total Sig. DEG",main="Liver Rapamycin Relative to Control",ylim=c(0,2500))

```

##Sig. DEG Subsets
```{r}

sL=length(unique(c(row.names(sC2),row.names(sC3),row.names(sC4),row.names(sC5),
                row.names(sR2),row.names(sR3),row.names(sR4),row.names(sR5))))
sRC=unique(c(row.names(sRC2),row.names(sRC3),row.names(sRC4),row.names(sRC5)))
sCL=unique(c(row.names(sC2),row.names(sC3),row.names(sC4),row.names(sC5)))
sRL=unique(c(row.names(sR2),row.names(sR3),row.names(sR4),row.names(sR5)))
sCLonly=setdiff(sCL,sRL)
sRLonly=setdiff(sRL,sCL)
sCLandRL=intersect(sCL,sRL)
sCLandRL=setdiff(sCLandRL,sRC)
```

##Control Only Sig. DEG Heatmap
```{r}

hmdata=as.data.frame(lmeancpm[sCLonly,])
hmcolors=colorpanel(100,"royalblue4","white","firebrick4")
hm=heatmaply(hmdata,scale="row",col=hmcolors,Colv = F, main="Genes that are Only Sig. DE in Control Liver",na.value = "white")

```

```{r}

order=hm$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,23)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],49,58))
order[,2]=as.numeric(substring(order[,2],49,58))
order[,3]=as.numeric(substring(order[,3],49,58))
order[,4]=as.numeric(substring(order[,4],49,58))
order[,5]=as.numeric(substring(order[,5],49,58))

colnames(order)=colnames(hmdata)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,1:5]


order[setdiff(row.names(order),row.names(sC2)),2]=NA
order[setdiff(row.names(order),row.names(sC3)),3]=NA
order[setdiff(row.names(order),row.names(sC4)),4]=NA
order[setdiff(row.names(order),row.names(sC5)),5]=NA

heatmaply(order,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .5,main="Liver Sig. DEG in Control Only",labRow = c(rep(NA,nrow(order))),col=hmcolors)

```

##Rapa Only Sig. DEG Heatmap
```{r}

hmdata=as.data.frame(lmeancpm[sRLonly,])
hmcolors=colorpanel(100,"royalblue4","white","firebrick4")
hm=heatmaply(hmdata,scale="row",col=hmcolors,Colv = F, main="Genes that are Only Sig. DE in Rapa Liver",na.value = "white")

```

```{r}

order=hm$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,23)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],49,58))
order[,6]=as.numeric(substring(order[,6],49,58))
order[,7]=as.numeric(substring(order[,7],49,58))
order[,8]=as.numeric(substring(order[,8],49,58))
order[,9]=as.numeric(substring(order[,9],49,58))

colnames(order)=colnames(hmdata)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,c(1,6:9)]


order[setdiff(row.names(order),row.names(sR2)),2]=NA
order[setdiff(row.names(order),row.names(sR3)),3]=NA
order[setdiff(row.names(order),row.names(sR4)),4]=NA
order[setdiff(row.names(order),row.names(sR5)),5]=NA

heatmaply(order,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .5,main="Liver Sig. DEG in Rapa Only",col=hmcolors,labRow = c(rep(NA,nrow(order))))

```

##Control and Rapa Sig. DEG Heatmap
```{r}

hmdata=as.data.frame(lmeancpm[sCLandRL,])
hmcolors=colorpanel(100,"royalblue4","white","firebrick4")
hm=heatmaply(hmdata,scale="row",col=hmcolors,Colv = F, main="Genes that are Sig. DE in Control and Rapa Liver",na.value = "white")

```

```{r}

order=hm$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,23)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],49,58))
order[,2]=as.numeric(substring(order[,2],49,58))
order[,3]=as.numeric(substring(order[,3],49,58))
order[,4]=as.numeric(substring(order[,4],49,58))
order[,5]=as.numeric(substring(order[,5],49,58))
order[,6]=as.numeric(substring(order[,6],49,58))
order[,7]=as.numeric(substring(order[,7],49,58))
order[,8]=as.numeric(substring(order[,8],49,58))
order[,9]=as.numeric(substring(order[,9],49,58))


colnames(order)=colnames(hmdata)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]


order[setdiff(row.names(order),row.names(sC2)),2]=NA
order[setdiff(row.names(order),row.names(sC3)),3]=NA
order[setdiff(row.names(order),row.names(sC4)),4]=NA
order[setdiff(row.names(order),row.names(sC5)),5]=NA
order[setdiff(row.names(order),row.names(sR2)),6]=NA
order[setdiff(row.names(order),row.names(sR3)),7]=NA
order[setdiff(row.names(order),row.names(sR4)),8]=NA
order[setdiff(row.names(order),row.names(sR5)),9]=NA

heatmaply(order,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .5,main="Sig. DEG in Control and Rapa Liver",col=hmcolors,labRow = c(rep(NA,nrow(order))))

```

##Control vs. Rapa Sig. DEG Heatmap
```{r}

hmdata=as.data.frame(lmeancpm[sRC,])
hmcolors=colorpanel(100,"royalblue4","white","firebrick4")
hm=heatmaply(hmdata,scale="row",col=hmcolors,Colv = F, main="Sig. DEG in Control vs Rapa Liver",na.value = "white")

```

```{r}

order=hm$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,23)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],49,58))
order[,2]=as.numeric(substring(order[,2],49,58))
order[,3]=as.numeric(substring(order[,3],49,58))
order[,4]=as.numeric(substring(order[,4],49,58))
order[,5]=as.numeric(substring(order[,5],49,58))
order[,6]=as.numeric(substring(order[,6],49,58))
order[,7]=as.numeric(substring(order[,7],49,58))
order[,8]=as.numeric(substring(order[,8],49,58))
order[,9]=as.numeric(substring(order[,9],49,58))


colnames(order)=colnames(hmdata)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]


order[setdiff(row.names(order),row.names(sC2)),2]=NA
order[setdiff(row.names(order),row.names(sC3)),3]=NA
order[setdiff(row.names(order),row.names(sC4)),4]=NA
order[setdiff(row.names(order),row.names(sC5)),5]=NA
order[setdiff(row.names(order),row.names(sR2)),6]=NA
order[setdiff(row.names(order),row.names(sR3)),7]=NA
order[setdiff(row.names(order),row.names(sR4)),8]=NA
order[setdiff(row.names(order),row.names(sR5)),9]=NA

heatmaply(order,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .5,main="Sig. DEG in Control vs Rapa Liver",col=hmcolors,labRow = c(rep(NA,nrow(order))))

```

