---
title: "Apoptosis GO Term Analysis"
author: "John Santiago"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=F}
##Load Libraries
library(org.Hs.eg.db)
library(PANDA)
library(heatmaply)
library(goseq)
library(GO.db)
library(edgeR)
library(topGO)
library(gplots)
library(visNetwork)

xx=as.list(org.Hs.egGO2ALLEGS)
xxx=as.list(org.Hs.egPATH2EG)
x1=as.list(org.Hs.egENSEMBL2EG)
x2=as.list(org.Hs.egSYMBOL)
x3=as.list(org.Hs.egENSEMBL)

ccpar=as.list(GOCCPARENTS)
ccchild=as.list(GOCCCHILDREN)

bppar=as.list(GOBPPARENTS)
bpchild=as.list(GOBPCHILDREN)

mfpar=as.list(GOMFPARENTS)
mfchild=as.list(GOMFCHILDREN)

term=as.list(GOTERM)

groups=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisMetadata.csv",row.names=1)
countdata=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisCountdata.csv",row.names=1)

cpmdata=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/cpmtable.csv",row.names=1)
meancpmdata=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/meancpmtable.csv",row.names=1)

CV2=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/EdgeROuptut_Viable_3Hvs0H.csv",row.names=1)
CV3=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/EdgeROuptut_Viable_6Hvs0H.csv",row.names=1)
CN2=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/EdgeROuptut_Nonviable_3Hvs0H.csv",row.names=1)
CN3=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/EdgeROuptut_Nonviable_6Hvs0H.csv",row.names=1)
EM2=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/EdgeROuptut_Apoptosis_3Hvs0H.csv",row.names=1)
EM3=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/EdgeROuptut_Apoptosis_6Hvs0H.csv",row.names=1)

CV2GO=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/GOseqOuptut_Viable_3Hvs0H.csv",row.names=1)
CV3GO=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/GOseqOuptut_Viable_6Hvs0H.csv",row.names=1)
CN2GO=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/GOseqOuptut_Nonviable_3Hvs0H.csv",row.names=1)
CN3GO=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/GOseqOuptut_Nonviable_6Hvs0H.csv",row.names=1)
EM2GO=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/GOseqOuptut_Apoptosis_3Hvs0H.csv",row.names=1)
EM3GO=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/GOseqOuptut_Apoptosis_6Hvs0H.csv",row.names=1)

sCV2=CV2[CV2$FDR<.05,]
sCV3=CV3[CV3$FDR<.05,]
sCV=unique(c(row.names(sCV2),row.names(sCV3)))

sCN2=CN2[CN2$FDR<.05,]
sCN3=CN3[CN3$FDR<.05,]
sCN=unique(c(row.names(sCN2),row.names(sCN3)))

sEM2=EM2[EM2$FDR<.05,]
sEM3=EM3[EM3$FDR<.05,]
sEM=unique(c(row.names(sEM2),row.names(sEM3)))

row.names(CV2GO)=CV2GO$term
row.names(CV3GO)=CV3GO$term

row.names(CN2GO)=CN2GO$term
row.names(CN3GO)=CN3GO$term

row.names(EM2GO)=EM2GO$term
row.names(EM3GO)=EM3GO$term

CV2GO$condition="CV2"
CV3GO$condition="CV3"

CN2GO$condition="CN2"
CN3GO$condition="CN3"

EM2GO$condition="EM2"
EM3GO$condition="EM3"


allsiggenes=unique(c(sCV,sCN,sEM))

```

```{r include=F}
##Find all children for the GO term "apoptotic process" GO:0006915

specificGO="GO:0006915"
temp=bpchild[specificGO]
edges=matrix(specificGO,nrow=length(temp[[1]]),ncol=4)
edges[,2]=names(temp[[1]])
edges[,3]=temp[[1]]
edges[,4]=1
children=temp[[1]]
tested=specificGO
names(children)=rep(2,length(children))

while(length(children)>0){
  tested=c(tested,children[1])
  temp=bpchild[children[1]]
  if(length(names(temp[[1]]))>0){
  tempedges=matrix(children[1],nrow=length(temp[[1]]),ncol=4)
  tempedges[,2]=names(temp[[1]])
  tempedges[,3]=temp[[1]]
  tempedges[,4]=names(children[1])
  edges=rbind(edges,tempedges)
  tempchildren=temp[[1]]
  names(tempchildren)=rep((as.numeric(names(children[1]))+1),length(tempchildren))
  children=c(children[-1],tempchildren)
  }else{
    children=children[-1]
  }
  i=1
  while(i<=length(children)){
  if(length(intersect(children[i],tested))==1){
    children=children[-i]
  }else{
    i=i+1
  }
  }
}

allchildren=unique(c(edges[,1],edges[,2]))

GO.wall=CV2GO
row.names(GO.wall)=GO.wall[,1]
i=1
while(i<=nrow(edges)){
  edges[i,1]=Term(term[[as.character(edges[i,1])]])
  edges[i,3]=Term(term[[as.character(edges[i,3])]])
  i=i+1
}


genesinallchildren=as.character(xx[[allchildren[1]]])
go.genes=intersect(as.character(unlist(x3[genesinallchildren])),row.names(cpmdata))
Apoptosis.gogenes=intersect(as.character(unlist(x3[genesinallchildren])),row.names(cpmdata))
Apoptosis.goterms=unique(c(edges[,1],edges[,3]))
ApoptosisEdges=edges

```


```{r include=F}
##Apoptosis Subgroup 1: "inflammatory cell apoptotic process" GO:0006925, "myeloid cell apoptotic process" GO:0033028, "leukocyte apoptotic process" GO:0071887

specificGO=c("GO:0006925","GO:0033028","GO:0071887")
temp=bpchild[specificGO[1]]
edges=matrix(specificGO[1],nrow=length(temp[[1]]),ncol=4)
edges[,2]=names(temp[[1]])
edges[,3]=temp[[1]]
edges[,4]=1
children=c(specificGO[-1],temp[[1]])
tested=specificGO[1]
names(children)=rep(2,length(children))

while(length(children)>0){
  tested=c(tested,children[1])
  temp=bpchild[children[1]]
  if(length(names(temp[[1]]))>0){
  tempedges=matrix(children[1],nrow=length(temp[[1]]),ncol=4)
  tempedges[,2]=names(temp[[1]])
  tempedges[,3]=temp[[1]]
  tempedges[,4]=names(children[1])
  edges=rbind(edges,tempedges)
  tempchildren=temp[[1]]
  names(tempchildren)=rep((as.numeric(names(children[1]))+1),length(tempchildren))
  children=c(children[-1],tempchildren)
  }else{
    children=children[-1]
  }
  i=1
  while(i<=length(children)){
  if(length(intersect(children[i],tested))==1){
    children=children[-i]
  }else{
    i=i+1
  }
  }
}

allchildren=unique(c(edges[,1],edges[,2]))

row.names(GO.wall)=GO.wall[,1]
i=1
while(i<=nrow(edges)){
  edges[i,1]=Term(term[[as.character(edges[i,1])]])
  edges[i,3]=Term(term[[as.character(edges[i,3])]])
  i=i+1
}


genesinallchildren=as.character(xx[[allchildren[1]]])
ApoptosisSubgroup1.gogenes=intersect(as.character(unlist(x3[genesinallchildren])),row.names(cpmdata))

ApoptosisSubgroup1.goterms=unique(c(edges[,1],edges[,3]))

edges=edges[c(1,1,1,1:nrow(edges)),]
edges[1:3,1]="apoptotic process"
edges[1:3,3]=c("inflammatory cell apoptotic process","myeloid cell apoptotic process","leukocyte apoptotic process")

```


```{r include=F}
##Apoptosis Subgroup 2: "intrinsic apoptotic signaling pathway" GO:0097193 

specificGO=c("GO:0097193")
temp=bpchild[specificGO[1]]
edges=matrix(specificGO[1],nrow=length(temp[[1]]),ncol=4)
edges[,2]=names(temp[[1]])
edges[,3]=temp[[1]]
edges[,4]=1
children=c(specificGO[-1],temp[[1]])
tested=specificGO[1]
names(children)=rep(2,length(children))

while(length(children)>0){
  tested=c(tested,children[1])
  temp=bpchild[children[1]]
  if(length(names(temp[[1]]))>0){
  tempedges=matrix(children[1],nrow=length(temp[[1]]),ncol=4)
  tempedges[,2]=names(temp[[1]])
  tempedges[,3]=temp[[1]]
  tempedges[,4]=names(children[1])
  edges=rbind(edges,tempedges)
  tempchildren=temp[[1]]
  names(tempchildren)=rep((as.numeric(names(children[1]))+1),length(tempchildren))
  children=c(children[-1],tempchildren)
  }else{
    children=children[-1]
  }
  i=1
  while(i<=length(children)){
  if(length(intersect(children[i],tested))==1){
    children=children[-i]
  }else{
    i=i+1
  }
  }
}

allchildren=unique(c(edges[,1],edges[,2]))

row.names(GO.wall)=GO.wall[,1]
i=1
while(i<=nrow(edges)){
  edges[i,1]=Term(term[[as.character(edges[i,1])]])
  edges[i,3]=Term(term[[as.character(edges[i,3])]])
  i=i+1
}


genesinallchildren=as.character(xx[[allchildren[1]]])
ApoptosisSubgroup2.gogenes=intersect(as.character(unlist(x3[genesinallchildren])),row.names(cpmdata))

ApoptosisSubgroup2.goterms=unique(c(edges[,1],edges[,3]))

edges=edges[c(1,1:nrow(edges)),]
edges[1,1]="apoptotic process"
edges[1,3]=c("intrinsic apoptotic signaling pathway")

```


```{r include=F}
##Apoptosis Subgroup 3: extrinsic apoptotic signaling pathway GO:0097191

specificGO=c("GO:0097191")
temp=bpchild[specificGO[1]]
edges=matrix(specificGO[1],nrow=length(temp[[1]]),ncol=4)
edges[,2]=names(temp[[1]])
edges[,3]=temp[[1]]
edges[,4]=1
children=c(specificGO[-1],temp[[1]])
tested=specificGO[1]
names(children)=rep(2,length(children))

while(length(children)>0){
  tested=c(tested,children[1])
  temp=bpchild[children[1]]
  if(length(names(temp[[1]]))>0){
  tempedges=matrix(children[1],nrow=length(temp[[1]]),ncol=4)
  tempedges[,2]=names(temp[[1]])
  tempedges[,3]=temp[[1]]
  tempedges[,4]=names(children[1])
  edges=rbind(edges,tempedges)
  tempchildren=temp[[1]]
  names(tempchildren)=rep((as.numeric(names(children[1]))+1),length(tempchildren))
  children=c(children[-1],tempchildren)
  }else{
    children=children[-1]
  }
  i=1
  while(i<=length(children)){
  if(length(intersect(children[i],tested))==1){
    children=children[-i]
  }else{
    i=i+1
  }
  }
}

allchildren=unique(c(edges[,1],edges[,2]))

row.names(GO.wall)=GO.wall[,1]
i=1
while(i<=nrow(edges)){
  edges[i,1]=Term(term[[as.character(edges[i,1])]])
  edges[i,3]=Term(term[[as.character(edges[i,3])]])
  i=i+1
}


genesinallchildren=as.character(xx[[allchildren[1]]])
ApoptosisSubgroup3.gogenes=intersect(as.character(unlist(x3[genesinallchildren])),row.names(cpmdata))

ApoptosisSubgroup3.goterms=unique(c(edges[,1],edges[,3]))


edges=edges[c(1,1:nrow(edges)),]
edges[1,1]="apoptotic process"
edges[1,3]=c("extrinsic apoptotic signaling pathway")

```

```{r include=F}
##Apoptosis Subgroup 4: "epithelial cell apoptotic process" GO:1904019

specificGO=c("GO:1904019")
temp=bpchild[specificGO[1]]
edges=matrix(specificGO[1],nrow=length(temp[[1]]),ncol=4)
edges[,2]=names(temp[[1]])
edges[,3]=temp[[1]]
edges[,4]=1
children=c(specificGO[-1],temp[[1]])
tested=specificGO[1]
names(children)=rep(2,length(children))

while(length(children)>0){
  tested=c(tested,children[1])
  temp=bpchild[children[1]]
  if(length(names(temp[[1]]))>0){
  tempedges=matrix(children[1],nrow=length(temp[[1]]),ncol=4)
  tempedges[,2]=names(temp[[1]])
  tempedges[,3]=temp[[1]]
  tempedges[,4]=names(children[1])
  edges=rbind(edges,tempedges)
  tempchildren=temp[[1]]
  names(tempchildren)=rep((as.numeric(names(children[1]))+1),length(tempchildren))
  children=c(children[-1],tempchildren)
  }else{
    children=children[-1]
  }
  i=1
  while(i<=length(children)){
  if(length(intersect(children[i],tested))==1){
    children=children[-i]
  }else{
    i=i+1
  }
  }
}

allchildren=unique(c(edges[,1],edges[,2]))

row.names(GO.wall)=GO.wall[,1]
i=1
while(i<=nrow(edges)){
  edges[i,1]=Term(term[[as.character(edges[i,1])]])
  edges[i,3]=Term(term[[as.character(edges[i,3])]])
  i=i+1
}


genesinallchildren=as.character(xx[[allchildren[1]]])
ApoptosisSubgroup4.gogenes=intersect(as.character(unlist(x3[genesinallchildren])),row.names(cpmdata))

ApoptosisSubgroup4.goterms=unique(c(edges[,1],edges[,3]))


edges=edges[c(1,1:nrow(edges)),]
edges[1,1]="apoptotic process"
edges[1,3]=c("epithelial cell apoptotic process")

```


```{r include=F}
##Apoptosis Subgroup 5: "protein insertion into mitochondrial membrane involved in apoptotic signaling pathway" GO:0001844

specificGO=c("GO:0001844")
temp=bpchild[specificGO[1]]
edges=matrix(specificGO[1],nrow=length(temp[[1]]),ncol=4)
edges[,2]=names(temp[[1]])
edges[,3]=temp[[1]]
edges[,4]=1
children=c(specificGO[-1],temp[[1]])
tested=specificGO[1]
names(children)=rep(2,length(children))

while(length(children)>0){
  tested=c(tested,children[1])
  temp=bpchild[children[1]]
  if(length(names(temp[[1]]))>0){
  tempedges=matrix(children[1],nrow=length(temp[[1]]),ncol=4)
  tempedges[,2]=names(temp[[1]])
  tempedges[,3]=temp[[1]]
  tempedges[,4]=names(children[1])
  edges=rbind(edges,tempedges)
  tempchildren=temp[[1]]
  names(tempchildren)=rep((as.numeric(names(children[1]))+1),length(tempchildren))
  children=c(children[-1],tempchildren)
  }else{
    children=children[-1]
  }
  i=1
  while(i<=length(children)){
  if(length(intersect(children[i],tested))==1){
    children=children[-i]
  }else{
    i=i+1
  }
  }
}

allchildren=unique(c(edges[,1],edges[,2]))

row.names(GO.wall)=GO.wall[,1]
i=1
while(i<=nrow(edges)){
  edges[i,1]=Term(term[[as.character(edges[i,1])]])
  edges[i,3]=Term(term[[as.character(edges[i,3])]])
  i=i+1
}


genesinallchildren=as.character(xx[[allchildren[1]]])
ApoptosisSubgroup5.gogenes=intersect(as.character(unlist(x3[genesinallchildren])),row.names(cpmdata))

ApoptosisSubgroup5.goterms=unique(c(edges[,1],edges[,3]))


edges=edges[c(1,1:nrow(edges)),]
edges[1,1]="apoptotic process"
edges[1,3]=c("protein insertion into mitochondrial membrane involved in apoptotic signaling pathway")

```




```{r, fig.height=15, fig.width=10}
allsGO=c(EM3GO$term[EM3GO$adjp<.05],EM2GO$term[EM2GO$adjp<.05],CN3GO$term[CN3GO$adjp<.05],CN2GO$term[CN2GO$adjp<.05],CV3GO$term[CV3GO$adjp<.05],CV2GO$term[CV2GO$adjp<.05])

group1=intersect(allsGO,ApoptosisSubgroup1.goterms)
names(group1)=c(rep("Inflammatory cell apoptotic process",length(group1)))
group2=intersect(allsGO,ApoptosisSubgroup2.goterms)
names(group2)=c(rep("Intrinsic apoptotic signaling pathway",length(group2)))
group3=intersect(allsGO,ApoptosisSubgroup3.goterms)
names(group3)=c(rep("Extrinsic apoptotic signaling pathway",length(group3)))
group4=intersect(allsGO,ApoptosisSubgroup4.goterms)
names(group4)=c(rep("Epithelial cell apoptotic process",length(group4)))
group5=intersect(allsGO,ApoptosisSubgroup5.goterms)
names(group5)=c(rep("Mitochondrial membrane associated apoptosis pathway",length(group5)))
group6=setdiff(intersect(allsGO,Apoptosis.goterms),c(group1,group2,group3,group4,group5))
names(group6)=c(rep("General Apoptosis",length(group6)))


dotplotterms=c(group1,group2,group3,group4,group5,group6)[56:1]
groups=names(dotplotterms)


num.genes=rbind(CV2GO[dotplotterms,],CV3GO[dotplotterms,],CN2GO[dotplotterms,],CN3GO[dotplotterms,],EM2GO[dotplotterms,],EM3GO[dotplotterms,])

num.genes$neg.log10.adjp=-(log(num.genes$adjp,base=10))
num.genes$neg.log10.adjp[num.genes$adjp>.05]=NA
num.genes$groups=factor(groups,levels=c("Intrinsic apoptotic signaling pathway","Inflammatory cell apoptotic process","Extrinsic apoptotic signaling pathway","Epithelial cell apoptotic process","Mitochondrial membrane associated apoptosis pathway","General Apoptosis"))

num.genes$term=factor(num.genes$term, levels = num.genes$term[1:56])
num.genes$sample=factor(num.genes$condition)


dotplot=ggplot(data=num.genes, aes(x= sample, y=term, color=numDEInCat,size=neg.log10.adjp)) +
  geom_point(alpha = 0.9) + 
  scale_color_gradient(low = "blue",high = "red3", space = "Lab", name="Num DE in Cat") +
  geom_vline(xintercept = c(2.5,4.5)) +
   facet_wrap(~groups,  ncol=1, strip.position = "left",scales="free")
dotplot


```

```{r  fig.height=10, fig.width=10}

refset=allsGO
originaledges=ApoptosisEdges
tempedges=originaledges
i=1
while(i<=nrow(tempedges)){
  tempedges[i,2]=length(intersect(c(tempedges[i,1]),refset))
  tempedges[i,4]=length(intersect(c(tempedges[i,3]),refset))
  
  i=i+1
}

newedges=tempedges[tempedges[,2]>0|tempedges[,4]>0,]

motifs <- unique(as.character(newedges[,1]))
genes <- unique(as.character(newedges[,3]))
parents=c(setdiff(motifs,genes))
nodeid=unique(c(genes,motifs))

nodegroups=rep("not sig",length(nodeid))
i=1
while(i<=length(nodegroups)){
  if(length(intersect(nodeid[i],group1))>0){
    nodegroups[i]="Inflammatory cell apoptotic process"
  }
    if(length(intersect(nodeid[i],group2))>0){
    nodegroups[i]="Intrinsic apoptotic signaling pathway"
    }
    if(length(intersect(nodeid[i],group3))>0){
    nodegroups[i]="Extrinsic apoptotic signaling pathway"
    }
    if(length(intersect(nodeid[i],group4))>0){
    nodegroups[i]="Epithelial cell apoptotic process"
    }
    if(length(intersect(nodeid[i],group5))>0){
    nodegroups[i]="Mitochondrial membrane associated apoptosis pathway"
    }
    if(length(intersect(nodeid[i],group6))>0){
    nodegroups[i]="General Apoptosis"
    }
  i=i+1
}

nodegroups[nodeid=="extrinsic apoptotic signaling pathway"]="Extrinsic apoptotic signaling pathway parent"

nodegroups[nodeid=="epithelial cell apoptotic process"]="Epithelial cell apoptotic process parent"

nodegroups[nodeid=="leukocyte apoptotic process"]="Inflammatory cell apoptotic process parent"
nodegroups[nodeid=="inflammatory cell apoptotic process"]="Inflammatory cell apoptotic process parent"
nodegroups[nodeid=="myeloid cell apoptotic process"]="Inflammatory cell apoptotic process parent"

nodegroups[nodeid=="intrinsic apoptotic signaling pathway"]="Intrinsic apoptotic signaling pathway parent"

nodegroups[nodeid=="protein insertion into mitochondrial membrane involved in apoptotic signaling pathway"]="Mitochondrial membrane associated apoptosis pathway parent"

nodegroups[nodeid=="apoptotic process"]="Parent Term"




nodes=data.frame(id=nodeid,group=nodegroups)
visedges=as.data.frame(newedges[,c(1,3)])
colnames(visedges)=c("from","to")
visNetwork(nodes,visedges)%>%
  visNodes(shape="box",mass=3)%>%
  visLayout(hierarchical=F, improvedLayout=T)%>%
  
  visGroups(groupname = "Parent Term", shape = "box", color = list(background = "firebrick", border="black"),font=list(color="white",size=100),physics=F)%>%
  
  visGroups(groupname = "Intrinsic apoptotic signaling pathway parent", shape = "box", color = list(background = "dodgerblue", border="black"),font=list(color="black",size=50),physics=F)%>%
  
  visGroups(groupname = "Inflammatory cell apoptotic process parent", shape = "box", color = list(background = "green", border="black"),font=list(color="white",size=50),physics=F)%>%
  
    visGroups(groupname = "Extrinsic apoptotic signaling pathway parent", shape = "box", color = list(background = "red", border="black"),font=list(color="white",size=50),physics=F)%>%  
  
    visGroups(groupname = "Epithelial cell apoptotic process parent", shape = "box", color = list(background = "yellow", border="black"),font=list(color="black",size=50),physics=F)%>%
  
    visGroups(groupname = "Mitochondrial membrane associated apoptosis pathway parent", shape = "box", color = list(background = "tan", border="black"),font=list(color="black",size=50),physics=F)%>%
  
    visGroups(groupname = "Intrinsic apoptotic signaling pathway", shape = "box", color = list(background = "dodgerblue", border="black"),font=list(color="black",size=50),physics=T)%>%
  
  visGroups(groupname = "Inflammatory cell apoptotic process", shape = "box", color = list(background = "green", border="black"),font=list(color="white",size=50),physics=T)%>%
  
    visGroups(groupname = "Extrinsic apoptotic signaling pathway", shape = "box", color = list(background = "red", border="black"),font=list(color="white",size=50),physics=T)%>%  
  
    visGroups(groupname = "Epithelial cell apoptotic process", shape = "box", color = list(background = "yellow", border="black"),font=list(color="black",size=50),physics=T)%>%
  
    visGroups(groupname = "Mitochondrial membrane associated apoptosis pathway", shape = "box", color = list(background = "tan", border="black"),font=list(color="black",size=25),physics=T)%>%
  
    visGroups(groupname = "General Apoptosis", shape = "box", color = list(background = "black", border="white"),font=list(color="white",size=50),physics=T)%>%
  
  visGroups(groupname = "not sig", shape = "dot", color = list(background = "white", border="black"),font=list(color="black"),physics=T)%>%
  
  ##visPhysics(solver="forceAtlas2Based", forceAtlas2Based = list(gravitationalConstant=-50, avoidOverlap=.1),enabled = T)%>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE)%>%
  visEdges(arrows='to')%>%
  visLegend(addNodes = list(list(label = "Intrinsic apoptotic signaling pathway parent", shape = "box", color = list(background = "dodgerblue", border="black"),font=list(color="black",size=50)),
                            list(label= "Inflammatory cell apoptotic process parent", shape = "box", color = list(background = "green", border="black"),font=list(color="white",size=50)),
                            list(label="Extrinsic apoptotic signaling pathway parent", shape = "box", color = list(background = "red", border="black"),font=list(color="black",size=50)),
                            list(label="Epithelial cell apoptotic process parent", shape = "box", color = list(background = "yellow", border="black"),font=list(color="black",size=50)),
                            list(label="Mitochondrial membrane associated apoptosis pathway parent", shape = "box", color = list(background = "tan", border="black"),font=list(color="black",size=50)),
                            list(label="General Apoptosis", shape = "box", color = list(background = "black", border="white"),font=list(color="white",size=50)),
                            list(label="not sig", shape = "dot", color = list(background = "white", border="black"),font=list(color="black",size=50))),useGroups = FALSE)


```

```{r include=F}
ApoptosisHMs=function(geneset,hmtitle){
hmd=CN2[geneset,rep(1,6)]
colnames(hmd)=c("CN3H","CN6H","CV3H","CV6H","EM3H","EM6H")
hmd[,1]=CN2[geneset,"logFC"]
hmd[,2]=CN3[geneset,"logFC"]
hmd[,3]=CV2[geneset,"logFC"]
hmd[,4]=CV3[geneset,"logFC"]
hmd[,5]=EM2[geneset,"logFC"]
hmd[,6]=EM3[geneset,"logFC"]

hmcolors=colorpanel(100,"royalblue4","grey","firebrick4")
hm=heatmaply(hmd,scale="none",trace="none",Colv = F,main=hmtitle,col=hmcolors, dendrogram = "row")


order=hm$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],48,58))
order[,2]=as.numeric(substring(order[,2],48,58))
order[,3]=as.numeric(substring(order[,3],48,58))
order[,4]=as.numeric(substring(order[,4],48,58))
order[,5]=as.numeric(substring(order[,5],48,58))
order[,6]=as.numeric(substring(order[,6],48,58))


colnames(order)=colnames(hmd)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]


order[setdiff(row.names(order),row.names(sCN2)),1]=NA
order[setdiff(row.names(order),row.names(sCN3)),2]=NA
order[setdiff(row.names(order),row.names(sCV2)),3]=NA
order[setdiff(row.names(order),row.names(sCV3)),4]=NA
order[setdiff(row.names(order),row.names(sEM2)),5]=NA
order[setdiff(row.names(order),row.names(sEM3)),6]=NA


return(order)
}
```

```{r}
geneset=intersect(Apoptosis.gogenes,allsiggenes)
hmtitle="Apoptotic Process GO terms"
sg1hmd=ApoptosisHMs(geneset,hmtitle)

hmcolors=colorpanel(100,"royalblue4","lightyellow","firebrick4")
heatmaply(sg1hmd,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)

```


```{r}
geneset=intersect(Apoptosis.gogenes,allsiggenes)
hmtitle="Apoptotic Process GO terms"

hmd=CN2[geneset,rep(1,6)]
colnames(hmd)=c("CN3H","CN6H","CV3H","CV6H","EM3H","EM6H")
hmd[,1]=CN2[geneset,"logFC"]
hmd[,2]=CN3[geneset,"logFC"]
hmd[,3]=CV2[geneset,"logFC"]
hmd[,4]=CV3[geneset,"logFC"]
hmd[,5]=EM2[geneset,"logFC"]
hmd[,6]=EM3[geneset,"logFC"]

hmcolors=colorpanel(100,"royalblue4","grey","firebrick4")
hm=heatmaply(hmd,scale="row",trace="none",Colv = F,main=hmtitle,col=hmcolors, dendrogram = "row")


order=hm$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],48,58))
order[,2]=as.numeric(substring(order[,2],48,58))
order[,3]=as.numeric(substring(order[,3],48,58))
order[,4]=as.numeric(substring(order[,4],48,58))
order[,5]=as.numeric(substring(order[,5],48,58))
order[,6]=as.numeric(substring(order[,6],48,58))


colnames(order)=colnames(hmd)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]


order[setdiff(row.names(order),row.names(sCN2)),1]=NA
order[setdiff(row.names(order),row.names(sCN3)),2]=NA
order[setdiff(row.names(order),row.names(sCV2)),3]=NA
order[setdiff(row.names(order),row.names(sCV3)),4]=NA
order[setdiff(row.names(order),row.names(sEM2)),5]=NA
order[setdiff(row.names(order),row.names(sEM3)),6]=NA

AllApoptosisDEG.meancpmdata=order
heatmaply(AllApoptosisDEG.meancpmdata,scale="none",trace="none",Colv = T,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)
```


```{r}
geneset=intersect(ApoptosisSubgroup1.gogenes,allsiggenes)
hmtitle="Inflammatory cell apoptotic process"
sg1hmd=ApoptosisHMs(geneset,hmtitle)
heatmaply(sg1hmd,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)
```

```{r}
geneset=intersect(ApoptosisSubgroup2.gogenes,allsiggenes)
hmtitle="Intrinsic apoptotic signaling pathway"
sg2hmd=ApoptosisHMs(geneset,hmtitle)

heatmaply(sg2hmd,scale="none",trace="none",Colv = T,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)
```

```{r}
geneset=intersect(ApoptosisSubgroup3.gogenes,allsiggenes)
hmtitle="Extrinsic apoptotic signaling pathway"
sg3hmd=ApoptosisHMs(geneset,hmtitle)

heatmaply(sg3hmd,scale="none",trace="none",Colv = T,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)
```

```{r}
geneset=intersect(ApoptosisSubgroup4.gogenes,allsiggenes)
hmtitle="Epithelial cell apoptotic process"
sg4hmd=ApoptosisHMs(geneset,hmtitle)

heatmaply(sg4hmd,scale="none",trace="none",Colv = T,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)
```

```{r}
geneset=intersect(ApoptosisSubgroup5.gogenes,allsiggenes)
hmtitle="Mitochondrial membrane associated apoptosis pathway"
sg5hmd=ApoptosisHMs(geneset,hmtitle)

heatmaply(sg5hmd,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)
```

```{r}
geneset=setdiff(intersect(allsiggenes,Apoptosis.gogenes),c(ApoptosisSubgroup1.gogenes,ApoptosisSubgroup2.gogenes,ApoptosisSubgroup3.gogenes,ApoptosisSubgroup4.gogenes,ApoptosisSubgroup5.gogenes))
hmtitle="General Apoptosis"
sg6hmd=ApoptosisHMs(geneset,hmtitle)

heatmaply(sg6hmd,scale="none",trace="none",Colv = T,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors)
```

```{r fig.width=5, fig.height=10}
totalhmd=rbind(rbind(rbind(sg1hmd,sg2hmd), rbind(sg3hmd,sg4hmd)), rbind(sg5hmd,sg6hmd))




hmtitle="Apoptosis GO terms"

side=c(rep("Inflammatory cell apoptotic process", nrow(sg1hmd)),
       rep("Intrinsic apoptotic signaling pathway",nrow(sg2hmd)),
       rep("Extrinsic apoptotic signaling pathway",nrow(sg3hmd)),
       rep("Epithelial cell apoptotic process",nrow(sg4hmd)),
       rep("Mitochondrial membrane associated apoptosis pathway",nrow(sg5hmd)),
       rep("General Apoptosis",nrow(sg6hmd)))

hmcolors=colorpanel(100,"royalblue4","lightgrey","firebrick4")

      heatmaply(totalhmd,scale="none",trace="none",Colv = T,Rowv=F,cexRow = .5,main=hmtitle,col=hmcolors,row_side_colors=side, limits=c(-10, 10))



##scale_fill_gradient_fun = ggplot2::scale_fill_gradientn( colours = c("blue", "yellow", "red"), values = scales::rescale(c(-1, 0, 1))))
      
      
```

























