---
title: "Lean Total DEG"
author: "John Santiago"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE}
library(rgl)
knitr::opts_chunk$set(echo = FALSE, fig.align="center")
knitr::knit_hooks$set(webgl = hook_webgl)
```

```{r include=F}
##Load Libraries
library(edgeR)
library(VennDiagram)
library(heatmaply)
library(gplots)

```

```{r include =F}
groups=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisMetadata.csv",row.names=1)
countdata=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisCountdata.csv",row.names=1)

##EdgeR comparisons
countdata=countdata[,row.names(groups)]
x <- countdata
group <- factor(groups$Group)
y <- DGEList(counts=x,group=group)
keep <- filterByExpr(y)
y <- y[keep,,keep.lib.sizes=FALSE] 
z <- calcNormFactors(y, method = "TMM") 
cpmdata=cpm(z)
design<-model.matrix(~0+groups$Group)
colnames(design) <- levels(group)
z = estimateGLMCommonDisp(z,design, verbose=T)
z = estimateGLMTrendedDisp(z,design)
z = estimateGLMTagwiseDisp(z,design)
fit <- glmFit(z, design)

##comparisons
##3 hour CN vs 0 hour CN
compare = makeContrasts((CN2-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CN2=G_X_E$table

##6 hour CN vs 0 hour CN
compare = makeContrasts((CN3-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CN3=G_X_E$table

##3 hour CV vs 0 hour CV
compare = makeContrasts((CV2-CV1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CV2=G_X_E$table

##6 hour CV vs 0 hour CV
compare = makeContrasts((CV3-CV1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CV3=G_X_E$table

##3 hour EM vs 0 hour EM
compare = makeContrasts((EM2-EM1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EM2=G_X_E$table

##6 hour EM vs 0 hour EM
compare = makeContrasts((EM3-EM1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EM3=G_X_E$table

##0 hour CV vs 0 hour CN
compare = makeContrasts((CV1-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CVCN1=G_X_E$table

##0 hour EM vs 0 hour CN
compare = makeContrasts((EM1-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCN1=G_X_E$table

##0 hour EM vs 0 hour CV
compare = makeContrasts((EM1-CV1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCV1=G_X_E$table

##3 hour CV vs 3 hour CN
compare = makeContrasts((CV2-CN2), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CVCN2=G_X_E$table

##3 hour EM vs 3 hour CN
compare = makeContrasts((EM2-CN2), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCN2=G_X_E$table

##3 hour EM vs 3 hour CV
compare = makeContrasts((EM2-CV2), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCV2=G_X_E$table

##6 hour CV vs 6 hour CN
compare = makeContrasts((CV3-CN3), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CVCN3=G_X_E$table

##6 hour EM vs 6 hour CN
compare = makeContrasts((EM3-CN3), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCN3=G_X_E$table

##6 hour EM vs 6 hour CV
compare = makeContrasts((EM3-CV3), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCV3=G_X_E$table

sCV2=CV2[CV2$FDR<.05,]
sCV3=CV3[CV3$FDR<.05,]
sCN2=CN2[CN2$FDR<.05,]
sCN3=CN3[CN3$FDR<.05,]
sEM2=EM2[EM2$FDR<.05,]
sEM3=EM3[EM3$FDR<.05,]

sCVCN1=CVCN1[CVCN1$FDR<.05,]
sEMCN1=EMCN1[EMCN1$FDR<.05,]
sEMCV1=EMCV1[EMCV1$FDR<.05,]

sCVCN2=CVCN2[CVCN2$FDR<.05,]
sEMCN2=EMCN2[EMCN2$FDR<.05,]
sEMCV2=EMCV2[EMCV2$FDR<.05,]

sCVCN3=CVCN3[CVCN3$FDR<.05,]
sEMCN3=EMCN3[EMCN3$FDR<.05,]
sEMCV3=EMCV3[EMCV3$FDR<.05,]
```

```{r}
ve=c(nrow(sCVCN1), nrow(sEMCN1),nrow(sEMCV1),NA,nrow(sCVCN2), nrow(sEMCN2),nrow(sEMCV2),NA,nrow(sCVCN3), nrow(sEMCN3),nrow(sEMCV3))

par(mar=c(7,4,4,5))
barplot(height=ve,names.arg = c("V vs NV 0H", "A vs NV 0H", "A vs V 0H",NA,"V vs NV 3H", "A vs NV 3H", "A vs V 3H",NA,"V vs NV 6H", "A vs NV 6H", "A vs V 6H"), xlab="", ylab="Total DEG", main="", col="gold3", ylim=c(0,1000),las=2)

```

```{r fig.height=5, fig.width=5}
ve=c(nrow(sCV2), nrow(sCV3),NA,nrow(sCN2),nrow(sCN3),NA,nrow(sEM2),nrow(sEM3))

barplot(height=ve,names.arg = c("Viable 3 Hours", "Viable 6 Hours",NA, "Non-Viable 3 Hours","Non-Viable 6 Hours",NA,"Apoptosis 3 Hours", "Apoptosis 6 Hours"), xlab="Hours NMP", ylab="Total DEG", main="Total DEG Induced by NMP \nwith or without Apoptosis Inhibitor", col=c("green3","green3",NA,"red","red",NA,"royalblue","royalblue"),cex.names = 1,ylim=c(0,5000))

```


<br />
##Comparing Apoptosis samples to Viable and Nonviable samples combined<br />
##Genes found to be DEGs at all time points indicate a potential batch effect<br />

```{r}

##EdgeR comparisons
countdata=countdata[,row.names(groups)]
x <- countdata
group <- factor(paste(substring(groups$Group,1,1),substring(groups$Group,3,3),sep=""))
y <- DGEList(counts=x,group=group)
keep <- filterByExpr(y)
y <- y[keep,,keep.lib.sizes=FALSE] 
z <- calcNormFactors(y, method = "TMM") 

design<-model.matrix(~0+group)
colnames(design) <- levels(group)
z = estimateGLMCommonDisp(z,design, verbose=T)
z = estimateGLMTrendedDisp(z,design)
z = estimateGLMTagwiseDisp(z,design)
fit <- glmFit(z, design)

##0 hour EM vs 0 hour CV and CN
compare = makeContrasts((E1-C1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EC1=G_X_E$table

##3 hour EM vs 3 hour CV and CN
compare = makeContrasts((E2-C2), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EC2=G_X_E$table

##3 hour EM vs 3 hour CV and CN
compare = makeContrasts((E3-C3), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EC3=G_X_E$table



sEC1=EC1[EC1$FDR<.05,]
sEC2=EC2[EC2$FDR<.05,]
sEC3=EC3[EC3$FDR<.05,]

##EdgeR comparisons
countdata=countdata[,row.names(groups)]
x <- countdata
group <- factor(substring(groups$Group,1,1))
y <- DGEList(counts=x,group=group)
keep <- filterByExpr(y)
y <- y[keep,,keep.lib.sizes=FALSE] 
z <- calcNormFactors(y, method = "TMM") 

design<-model.matrix(~0+group)
colnames(design) <- levels(group)
z = estimateGLMCommonDisp(z,design, verbose=T)
z = estimateGLMTrendedDisp(z,design)
z = estimateGLMTagwiseDisp(z,design)
fit <- glmFit(z, design)

##0 hour EM vs 0 hour CV and CN
compare = makeContrasts((E-C), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EC=G_X_E$table

sEC=EC[EC$FDR<.05,]

##Sample titles as strings. Only fill in up to your number of selected categories
set1="0 Hour Sig. DE"
set2="3 Hour Sig. DE"
set3="6 Hour Sig. DE"
set4="All Times Combined Sig.DE"

  
##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
s1=row.names(sEC1)
s2=row.names(sEC2)
s3=row.names(sEC3)
s4=row.names(sEC)

grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1)

```
<br /><br /><br />
##0 Hour "Batch Effect" genes
```{r}
hmcolors=colorpanel(100,"royalblue4","white","firebrick4")
hmdata=cpmdata
meanhmdata=data.frame(Means=rowMeans(hmdata))

heatmaply(hmdata[s1,],Colv=F,col=hmcolors,scale="row",main = "Time 0 DEGs")
hist(meanhmdata[s1,],breaks=20,
     main="Mean Expression of all sDEG for 0H ",
     xlab="100% of 0H sDEG")

hist(meanhmdata[intersect(s1,row.names(meanhmdata)[meanhmdata$Means<2000]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 2000",
     xlab=paste(signif((length(meanhmdata[intersect(s1,row.names(meanhmdata)[meanhmdata$Means<2000]),])/(length(s1)))*100,digits=3),"% of 0H sDEG",sep= ""))

hist(meanhmdata[intersect(s1,row.names(meanhmdata)[meanhmdata$Means<200]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 200",
     xlab=paste(signif((length(meanhmdata[intersect(s1,row.names(meanhmdata)[meanhmdata$Means<200]),])/(length(s1)))*100,digits=3),"% of 0H sDEG",sep= ""))

hist(meanhmdata[intersect(s1,row.names(meanhmdata)[meanhmdata$Means<50]),],breaks=10,
     main="Mean Expression for genes with Mean CPM < 50",
     xlab=paste(signif((length(meanhmdata[intersect(s1,row.names(meanhmdata)[meanhmdata$Means<50]),])/(length(s1)))*100,digits=3),"% of 0H sDEG",sep= ""))

```

<br /><br /><br />
##3 Hour "Batch Effect" genes
```{r}

heatmaply(hmdata[s2,],Colv=F,col=hmcolors,scale="row",main="Time 3H DEGs")

hist(meanhmdata[s2,],breaks=20,
     main="Mean Expression of all sDEG for 3H ",
     xlab="100% of 3H sDEG")

hist(meanhmdata[intersect(s2,row.names(meanhmdata)[meanhmdata$Means<2000]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 2000",
     xlab=paste(signif((length(meanhmdata[intersect(s2,row.names(meanhmdata)[meanhmdata$Means<2000]),])/(length(s2)))*100,digits=3),"% of 3H sDEG",sep= ""))

hist(meanhmdata[intersect(s2,row.names(meanhmdata)[meanhmdata$Means<200]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 200",
     xlab=paste(signif((length(meanhmdata[intersect(s2,row.names(meanhmdata)[meanhmdata$Means<200]),])/(length(s2)))*100,digits=3),"% of 3H sDEG",sep= ""))

hist(meanhmdata[intersect(s2,row.names(meanhmdata)[meanhmdata$Means<50]),],breaks=10,
     main="Mean Expression for genes with Mean CPM < 50",
     xlab=paste(signif((length(meanhmdata[intersect(s2,row.names(meanhmdata)[meanhmdata$Means<50]),])/(length(s2)))*100,digits=3),"% of 3H sDEG",sep= ""))

```

<br /><br /><br />
##6 Hour "Batch Effect" genes
```{r}
heatmaply(hmdata[s3,],Colv=F,col=hmcolors,scale="row",main="Time 6H DEGs")

hist(meanhmdata[s3,],breaks=20,
     main="Mean Expression of all sDEG for 6H ",
     xlab="100% of 6H sDEG")

hist(meanhmdata[intersect(s3,row.names(meanhmdata)[meanhmdata$Means<2000]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 2000",
     xlab=paste(signif((length(meanhmdata[intersect(s3,row.names(meanhmdata)[meanhmdata$Means<2000]),])/(length(s3)))*100,digits=3),"% of 6H sDEG",sep= ""))

hist(meanhmdata[intersect(s3,row.names(meanhmdata)[meanhmdata$Means<200]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 200",
     xlab=paste(signif((length(meanhmdata[intersect(s3,row.names(meanhmdata)[meanhmdata$Means<200]),])/(length(s3)))*100,digits=3),"% of 6H sDEG",sep= ""))

hist(meanhmdata[intersect(s3,row.names(meanhmdata)[meanhmdata$Means<50]),],breaks=10,
     main="Mean Expression for genes with Mean CPM < 50",
     xlab=paste(signif((length(meanhmdata[intersect(s3,row.names(meanhmdata)[meanhmdata$Means<50]),])/(length(s3)))*100,digits=3),"% of 6H sDEG",sep= ""))

```
<br /><br /><br />
##All times "Batch Effect" genes
```{r}
heatmaply(hmdata[s4,],Colv=F,col=hmcolors,scale="row",main="All Times DEGs")

hist(meanhmdata[s4,],breaks=20,
     main="Mean Expression of all sDEG for All Times ",
     xlab="100% of All Times sDEG")

hist(meanhmdata[intersect(s4,row.names(meanhmdata)[meanhmdata$Means<2000]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 2000",
     xlab=paste(signif((length(meanhmdata[intersect(s4,row.names(meanhmdata)[meanhmdata$Means<2000]),])/(length(s4)))*100,digits=3),"% of All Times sDEG",sep= ""))

hist(meanhmdata[intersect(s4,row.names(meanhmdata)[meanhmdata$Means<200]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 200",
     xlab=paste(signif((length(meanhmdata[intersect(s4,row.names(meanhmdata)[meanhmdata$Means<200]),])/(length(s4)))*100,digits=3),"% of All Times sDEG",sep= ""))

hist(meanhmdata[intersect(s4,row.names(meanhmdata)[meanhmdata$Means<50]),],breaks=10,
     main="Mean Expression for genes with Mean CPM < 50",
     xlab=paste(signif((length(meanhmdata[intersect(s4,row.names(meanhmdata)[meanhmdata$Means<50]),])/(length(s4)))*100,digits=3),"% of All Times sDEG",sep= ""))

```

<br /><br /><br />
##Conserved across all timepoints (Consistent)
```{r}
s5=intersect(intersect(s1,s2),s3)

heatmaply(hmdata[s5,],Colv=F,col=hmcolors,scale="row",main="Consistent DEGs")

hist(meanhmdata[s5,],breaks=20,
     main="Mean Expression of all Consistent sDEG",
     xlab="100% of Consistent sDEG")

hist(meanhmdata[intersect(s5,row.names(meanhmdata)[meanhmdata$Means<2000]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 2000",
     xlab=paste(signif((length(meanhmdata[intersect(s5,row.names(meanhmdata)[meanhmdata$Means<2000]),])/(length(s5)))*100,digits=3),"% of Consistent sDEG",sep= ""))

hist(meanhmdata[intersect(s5,row.names(meanhmdata)[meanhmdata$Means<200]),],breaks=20,
     main="Mean Expression for genes with Mean CPM < 200",
     xlab=paste(signif((length(meanhmdata[intersect(s5,row.names(meanhmdata)[meanhmdata$Means<200]),])/(length(s5)))*100,digits=3),"% of Consistent sDEG",sep= ""))

hist(meanhmdata[intersect(s5,row.names(meanhmdata)[meanhmdata$Means<50]),],breaks=10,
     main="Mean Expression for genes with Mean CPM < 50",
     xlab=paste(signif((length(meanhmdata[intersect(s5,row.names(meanhmdata)[meanhmdata$Means<50]),])/(length(s5)))*100,digits=3),"% of Consistent sDEG",sep= ""))



```

