---
title: "Top 10 PCA Genes"
author: "John Santiago"
date: "5/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=F}

library(gplots)
library(heatmaply)
library("biomaRt")
library("goseq")
library(plot3D)

ensembl = useMart("ensembl",dataset="hsapiens_gene_ensembl")
go_slim=getBM(attributes="goslim_goa_accession",mart=ensembl)
##reactome=getBM(attributes = "reactome",mart=ensembl)
##kegg_enzyme=getBM(attributes="kegg_enzyme", mart=ensembl)

cpmdata=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/cpmtable.csv",row.names=1)
groups=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisMetadata.csv",row.names=1)
meancpm=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisMeanCPMdata.csv",row.names=1)

cpmdata=cpmdata[,c(1,3,6,9,12,2,4,7,10,13,5,8,11,14,15,18,21,24,27,16,19,22,25,28,17,20,23,26,29,30,33 ,36,39,42,31,34,37,40,43,32,35,38,41,44)]
groups=groups[colnames(cpmdata),]

colnames(cpmdata)=groups[colnames(cpmdata),"Library.ID"]
row.names(groups)=groups$Library.ID

ID.conversion=getBM(attributes=c("ensembl_gene_id","external_gene_name"),mart=ensembl)
row.names(ID.conversion)=ID.conversion[,1]
ID.conversion[ID.conversion[,2]=="",2]=ID.conversion[ID.conversion[,2]=="",1]
ID.conversion=ID.conversion[row.names(cpmdata),]


##pca <- prcomp(t(cpmdata[,1:29]), scale.=TRUE) 
##gr <- factor(row.names(groups[1:29,]))

pca <- prcomp(t(cpmdata), scale.=TRUE) 
gr <- factor(row.names(groups))
contribution=pca$rotation

##these add up to the total variation attributed to PC2 (or whatever PC you pick)
PCcontribute=contribution[,"PC2"]

##These are the percent of the total PC2 variation that each gene contributes.
percents=(PCcontribute*PCcontribute)

##Top of the list is the highest contributor to PC2 variation
percents=percents[order(percents,decreasing=T)]

##i=1
##meancpm=cpmdata[,1:9]
##names(meancpm)=c("CN1","CN2","CN3","CV1","CV2","CV3","EM1","EM2","EM3")
##while(i <= nrow(meancpm)){
##        meancpm[i,1]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CN1"]))
##        meancpm[i,2]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CN2"]))
##        meancpm[i,3]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CN3"])) 
##        
##        meancpm[i,4]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CV1"]))
##        meancpm[i,5]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CV2"]))
##        meancpm[i,6]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CV3"]))  
##        
##        meancpm[i,7]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="EM1"]))
##        meancpm[i,8]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="EM2"]))
##        meancpm[i,9]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="EM3"]))  
##i=i+1}

##meancpm= meancpm[rowSums(meancpm)!=0,]

##write.csv(meancpm, "/Users/johncsantiago/Documents/GitHub/SData/Apoptosis Code/ApoptosisMeanCPMdata.csv")

```

```{r}

PC1contribute=contribution[,1]
PC1contribute=PC1contribute[order(PC1contribute,decreasing=T)]

PC2contribute=contribution[,2]
PC2contribute=PC2contribute[order(PC2contribute,decreasing=T)]

PC3contribute=contribution[,3]
PC3contribute=PC3contribute[order(PC3contribute,decreasing=T)]

PCcontribute=PC2contribute
loading=(PCcontribute)
eigs <- pca$sdev^2
ve=(eigs / sum(eigs))*100
percent.variation=signif(ve,4)

##The column sum of squares of the loadings (pca$rotation) are the variances of PCs.
percents=(PCcontribute*PCcontribute)
percents=percents[order(percents,decreasing=T)]



loading=loading[names(percents)]
percent2=percents


temppercent=0
i=1
while(i<=length(percents)){
  percents[i]=percents[i]+temppercent
  temppercent=percents[i]
  i=i+1
}

##percents=percents[loading[names(percents)]>0]


hmd=names(percents)[percents<=.1]


toppc1=hmd
hmd=cpmdata[(hmd),]
hmd=cpmdata[row.names(hmd),]

hmcolors=colorpanel(100,"royalblue4","white","firebrick4")

side_colors=colorpanel(100,"grey","gold","green")

atimecolors=groups$Time
timecolors[timecolors=="0"]="darkgrey"
timecolors[timecolors=="3"]="gold3"
timecolors[timecolors=="6"]="green4"
names(timecolors)=groups$Time


```

```{r fig.width=5,fig.height=5, fig.align="center"}
allhm=heatmaply(hmd,scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row",col_side_colors = (groups$Time), col_side_palette = timecolors)
allhm
```


```{r fig.width=5,fig.height=5, fig.align="center"}
hmd2=hmd
i=1
while(i<=nrow(hmd2)){
  hmd2[i,hmd2[i,]<1]=1

  if(sum(hmd2[i,]<22)){
     hmd2[i,]=NA
  }
  i=i+1
}
hmd2=na.omit(hmd2)


##hmd2=log10(hmd2)
row.names(hmd2)=ID.conversion[row.names(hmd2),2]
heatmaply(hmd2,scale="row",trace="none",Colv = F,Rowv=T,cexRow =1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row",col_side_colors = (groups$Time), col_side_palette = timecolors)

```

```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(hmd2[,-6],scale="row",trace="none",Colv = F,Rowv=T,cexRow = 1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row",col_side_colors = (groups$Time)[-6], col_side_palette = timecolors[-6])

```





```{r fig.width=5,fig.height=5, fig.align="center"}
meanhmd=heatmaply(meancpm[row.names(hmd),],scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row")
meanhmd
```

```{r}

i=1
meancpm=cpmdata[,1:9]
names(meancpm)=c("CN1","CN2","CN3","CV1","CV2","CV3","EM1","EM2","EM3")
tempcpmdata=cpmdata
cpmdata=tempcpmdata[,-6]
while(i <= nrow(meancpm)){
        meancpm[i,1]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CN1"]))
        meancpm[i,2]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CN2"]))
        meancpm[i,3]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CN3"])) 
        
        meancpm[i,4]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CV1"]))
        meancpm[i,5]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CV2"]))
        meancpm[i,6]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="CV3"]))  
        
        meancpm[i,7]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="EM1"]))
        meancpm[i,8]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="EM2"]))
        meancpm[i,9]=mean(as.numeric(cpmdata[i,substring(colnames(cpmdata),1,3)=="EM3"]))  
i=i+1}

meancpm= meancpm[rowSums(meancpm)!=0,]
cpmdata=tempcpmdata
tempmeancpm=meancpm

meancpm=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisMeanCPMdata.csv",row.names=1)

```

```{r fig.width=5,fig.height=5, fig.align="center"}
tempmeanhmd=heatmaply(tempmeancpm[row.names(hmd),],scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row")
tempmeanhmd
```

```{r}

order=meancpm$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],47,58))
order[,2]=as.numeric(substring(order[,2],47,58))
order[,3]=as.numeric(substring(order[,3],47,58))
order[,4]=as.numeric(substring(order[,4],47,58))
order[,5]=as.numeric(substring(order[,5],47,58))
order[,6]=as.numeric(substring(order[,6],47,58))
order[,7]=as.numeric(substring(order[,7],47,58))
order[,8]=as.numeric(substring(order[,8],47,58))
order[,9]=as.numeric(substring(order[,9],47,58))

colnames(order)=colnames(meancpm)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]

order[setdiff(row.names(order),row.names(sCN2)),2]=NA
order[setdiff(row.names(order),row.names(sCN3)),3]=NA

order[setdiff(row.names(order),row.names(sCV2)),5]=NA
order[setdiff(row.names(order),row.names(sCV3)),6]=NA

order[setdiff(row.names(order),row.names(sEM2)),8]=NA
order[setdiff(row.names(order),row.names(sEM3)),9]=NA
meanorder=order
```


```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(meanorder,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution",col=hmcolors, dendrogram = "none")

```

```{r fig.width=5,fig.height=5, fig.align="center"}
hmd2=tempmeancpm[row.names(hmd),]
i=1
while(i<=nrow(hmd2)){
  hmd2[i,hmd2[i,]<1]=.001

  if(sum(hmd2[i,]<6)){
     hmd2[i,]=NA
  }
  i=i+1
}
hmd2=na.omit(hmd2)
tempmeanhmd2=(hmd2)
##ensembl = useMart("ensembl",dataset="hsapiens_gene_ensembl")
##ID.conversion=getBM(attributes=c("ensembl_gene_id","external_gene_name"),mart=ensembl)
row.names(ID.conversion)=ID.conversion[,1]
##hmd2=log10(hmd2)
row.names(hmd2)=ID.conversion[row.names(hmd2),2]
heatmaply(hmd2,scale="row",trace="none",Colv = F,Rowv=T,cexRow =1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row")
tempmeanhmd2=heatmaply(tempmeanhmd2,scale="row",trace="none",Colv = F,Rowv=T,cexRow =1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row")
```


```{r}

heatmaply(log10(hmd2),scale="none",trace="none",Colv = F,Rowv=T,cexRow =1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row")


```


```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(tempmeancpm[row.names(hmd2),],scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Top 10% PC1 Contribution: All Samples",col=hmcolors, dendrogram = "row")

```


```{r}

order=tempmeanhmd2$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],47,58))
order[,2]=as.numeric(substring(order[,2],47,58))
order[,3]=as.numeric(substring(order[,3],47,58))
order[,4]=as.numeric(substring(order[,4],47,58))
order[,5]=as.numeric(substring(order[,5],47,58))
order[,6]=as.numeric(substring(order[,6],47,58))
order[,7]=as.numeric(substring(order[,7],47,58))
order[,8]=as.numeric(substring(order[,8],47,58))
order[,9]=as.numeric(substring(order[,9],47,58))

colnames(order)=colnames(meancpm)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]

order[setdiff(row.names(order),row.names(sCN2)),2]=NA
order[setdiff(row.names(order),row.names(sCN3)),3]=NA

order[setdiff(row.names(order),row.names(sCV2)),5]=NA
order[setdiff(row.names(order),row.names(sCV3)),6]=NA

order[setdiff(row.names(order),row.names(sEM2)),8]=NA
order[setdiff(row.names(order),row.names(sEM3)),9]=NA
meanorder2=order
row.names(meanorder2)=ID.conversion[row.names(meanorder2),2]

```


```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(meanorder2,scale="none",trace="none",Colv = F,Rowv=F,cexRow = 1,main="Top 10% PC1 Contribution",col=hmcolors, dendrogram = "none")

```



```{r}

order=allhm$x$data[[1]]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],48,58))
order[,2]=as.numeric(substring(order[,2],48,58))
order[,3]=as.numeric(substring(order[,3],48,58))
order[,4]=as.numeric(substring(order[,4],48,58))
order[,5]=as.numeric(substring(order[,5],48,58))
order[,6]=as.numeric(substring(order[,6],48,58))
order[,7]=as.numeric(substring(order[,7],48,58))
order[,8]=as.numeric(substring(order[,8],48,58))
order[,9]=as.numeric(substring(order[,9],48,58))
order[,10]=as.numeric(substring(order[,10],48,58))
order[,11]=as.numeric(substring(order[,11],48,58))
order[,12]=as.numeric(substring(order[,12],48,58))
order[,13]=as.numeric(substring(order[,13],48,58))
order[,14]=as.numeric(substring(order[,14],48,58))

order[,15]=as.numeric(substring(order[,15],48,58))
order[,16]=as.numeric(substring(order[,16],48,58))
order[,17]=as.numeric(substring(order[,17],48,58))
order[,18]=as.numeric(substring(order[,18],48,58))
order[,19]=as.numeric(substring(order[,19],48,58))
order[,20]=as.numeric(substring(order[,20],48,58))
order[,21]=as.numeric(substring(order[,21],48,58))
order[,22]=as.numeric(substring(order[,22],48,58))
order[,23]=as.numeric(substring(order[,23],48,58))
order[,24]=as.numeric(substring(order[,24],48,58))
order[,25]=as.numeric(substring(order[,25],48,58))
order[,26]=as.numeric(substring(order[,26],48,58))
order[,27]=as.numeric(substring(order[,27],48,58))
order[,28]=as.numeric(substring(order[,28],48,58))
order[,29]=as.numeric(substring(order[,29],48,58))

order[,30]=as.numeric(substring(order[,30],48,58))
order[,31]=as.numeric(substring(order[,31],48,58))
order[,32]=as.numeric(substring(order[,32],48,58))
order[,33]=as.numeric(substring(order[,33],48,58))
order[,34]=as.numeric(substring(order[,34],48,58))
order[,35]=as.numeric(substring(order[,35],48,58))
order[,36]=as.numeric(substring(order[,36],48,58))
order[,37]=as.numeric(substring(order[,37],48,58))
order[,38]=as.numeric(substring(order[,38],48,58))
order[,39]=as.numeric(substring(order[,39],48,58))
order[,40]=as.numeric(substring(order[,40],48,58))
order[,41]=as.numeric(substring(order[,41],48,58))
order[,42]=as.numeric(substring(order[,42],48,58))
order[,43]=as.numeric(substring(order[,43],48,58))
order[,44]=as.numeric(substring(order[,44],48,58))

colnames(order)=colnames(hmd)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]

allorder=order

```


```{r fig.width=5,fig.height=5, fig.align="left"}

heatmaply(order[,1:14],scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution: Nonviable Samples",col=hmcolors, dendrogram = "none",col_side_colors = (groups$Time[1:14]), col_side_palette = timecolors)

```

```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(order[,15:29],scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution: Viable Samples",col=hmcolors, dendrogram = "none",col_side_colors = (groups$Time[15:29]), col_side_palette = timecolors)

```



```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(order[,30:44],scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution: Emricasan Samples",col=hmcolors, dendrogram = "none",col_side_colors = (groups$Time[30:44]), col_side_palette = timecolors)

```


```{r fig.width=5,fig.height=5, fig.align="center"}
meanhmd=heatmaply(meancpm[row.names(order),],scale="row",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution",col=hmcolors, dendrogram = "none")
meanhmd
```



```{r}

groups=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisMetadata.csv",row.names=1)

countdata=read.csv("https://raw.githubusercontent.com/johncsantiago/SData/master/Apoptosis%20Code/ApoptosisCountdata.csv",row.names=1)

##EdgeR comparisons
countdata=countdata[,row.names(groups)]
x <- countdata
group <- factor(groups$Group)
y <- DGEList(counts=x,group=group)
keep <- filterByExpr(y)
y <- y[keep,,keep.lib.sizes=FALSE] 
z <- calcNormFactors(y, method = "TMM") 
cpmdata=cpm(z)
design<-model.matrix(~0+groups$Group)
colnames(design) <- levels(group)
z = estimateGLMCommonDisp(z,design, verbose=T)
z = estimateGLMTrendedDisp(z,design)
z = estimateGLMTagwiseDisp(z,design)
fit <- glmFit(z, design)

##comparisons
##3 hour CN vs 0 hour CN
compare = makeContrasts((CN2-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CN2=G_X_E$table

##6 hour CN vs 0 hour CN
compare = makeContrasts((CN3-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CN3=G_X_E$table

##3 hour CV vs 0 hour CV
compare = makeContrasts((CV2-CV1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CV2=G_X_E$table

##6 hour CV vs 0 hour CV
compare = makeContrasts((CV3-CV1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CV3=G_X_E$table

##3 hour EM vs 0 hour EM
compare = makeContrasts((EM2-EM1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EM2=G_X_E$table

##6 hour EM vs 0 hour EM
compare = makeContrasts((EM3-EM1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EM3=G_X_E$table

##0 hour CV vs 0 hour CN
compare = makeContrasts((CV1-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CVCN1=G_X_E$table

##0 hour EM vs 0 hour CN
compare = makeContrasts((EM1-CN1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCN1=G_X_E$table

##0 hour EM vs 0 hour CV
compare = makeContrasts((EM1-CV1), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCV1=G_X_E$table

##3 hour CV vs 3 hour CN
compare = makeContrasts((CV2-CN2), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CVCN2=G_X_E$table

##3 hour EM vs 3 hour CN
compare = makeContrasts((EM2-CN2), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCN2=G_X_E$table

##3 hour EM vs 3 hour CV
compare = makeContrasts((EM2-CV2), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCV2=G_X_E$table

##6 hour CV vs 6 hour CN
compare = makeContrasts((CV3-CN3), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
CVCN3=G_X_E$table

##6 hour EM vs 6 hour CN
compare = makeContrasts((EM3-CN3), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCN3=G_X_E$table

##6 hour EM vs 6 hour CV
compare = makeContrasts((EM3-CV3), levels=design)
lrt <- glmLRT(fit,contrast=as.vector(compare))		
G_X_E<-topTags(lrt,adjust.method="BH",n = nrow(z$counts), sort.by="PValue")
EMCV3=G_X_E$table

sCV2=CV2[CV2$FDR<.05,]
sCV3=CV3[CV3$FDR<.05,]
sCN2=CN2[CN2$FDR<.05,]
sCN3=CN3[CN3$FDR<.05,]
sEM2=EM2[EM2$FDR<.05,]
sEM3=EM3[EM3$FDR<.05,]

allsigs=unique(c(row.names(sCV2),row.names(sCV3),row.names(sCN2),row.names(sCN3),row.names(sEM2),row.names(sEM3)))

FCdata=meancpm[,c(2,3,5,6,8,9)]
FCdata[,1]=CN2[row.names(FCdata),"logFC"]
FCdata[,2]=CN3[row.names(FCdata),"logFC"]
FCdata[,3]=CV2[row.names(FCdata),"logFC"]
FCdata[,4]=CV3[row.names(FCdata),"logFC"]
FCdata[,5]=EM2[row.names(FCdata),"logFC"]
FCdata[,6]=EM3[row.names(FCdata),"logFC"]


```



```{r}

order=tempmeanhmd$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],47,58))
order[,2]=as.numeric(substring(order[,2],47,58))
order[,3]=as.numeric(substring(order[,3],47,58))
order[,4]=as.numeric(substring(order[,4],47,58))
order[,5]=as.numeric(substring(order[,5],47,58))
order[,6]=as.numeric(substring(order[,6],47,58))
order[,7]=as.numeric(substring(order[,7],47,58))
order[,8]=as.numeric(substring(order[,8],47,58))
order[,9]=as.numeric(substring(order[,9],47,58))

colnames(order)=colnames(meancpm)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]

order[setdiff(row.names(order),row.names(sCN2)),2]=NA
order[setdiff(row.names(order),row.names(sCN3)),3]=NA

order[setdiff(row.names(order),row.names(sCV2)),5]=NA
order[setdiff(row.names(order),row.names(sCV3)),6]=NA

order[setdiff(row.names(order),row.names(sEM2)),8]=NA
order[setdiff(row.names(order),row.names(sEM3)),9]=NA
meanorder=order
```


```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(meanorder,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution",col=hmcolors, dendrogram = "none")

```





```{r fig.width=5,fig.height=5, fig.align="center"}
FChmd=heatmaply(FCdata[row.names(order),],scale="row",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution",col=hmcolors, dendrogram = "none")
FChmd
```



```{r}

order=FChmd$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],47,58))
order[,2]=as.numeric(substring(order[,2],47,58))
order[,3]=as.numeric(substring(order[,3],47,58))
order[,4]=as.numeric(substring(order[,4],47,58))
order[,5]=as.numeric(substring(order[,5],47,58))
order[,6]=as.numeric(substring(order[,6],47,58))


colnames(order)=colnames(FCdata)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]

order[setdiff(row.names(order),row.names(sCN2)),1]=NA
order[setdiff(row.names(order),row.names(sCN3)),2]=NA

order[setdiff(row.names(order),row.names(sCV2)),3]=NA
order[setdiff(row.names(order),row.names(sCV3)),4]=NA

order[setdiff(row.names(order),row.names(sEM2)),5]=NA
order[setdiff(row.names(order),row.names(sEM3)),6]=NA
FCorder=order
```



```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(FCorder,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution",col=hmcolors, dendrogram = "none")

```

```{r}

##randomsample=sample(row.names(cpmdata), size=nrow(order),replace=F)

sigs=row.names(hmd)
##sigs=randomsample
bg=cpmdata[,1:2]
bg[,1]=0
bg[sigs,1]=1
genes=bg[,1]
names(genes)=row.names(bg)
go=getgo(names(genes),"hg19","ensGene")
go_slim2cat=lapply(go,function(x){ x[x %in% go_slim[[1]]]  })
pwf=nullp(genes,"hg19","ensGene")

GO.wall=goseq(pwf,"hg19","ensGene")
GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
sig.GO=GO.wall[GO.wall$adjp<.05,c("category","term","ontology", "numDEInCat" ,"adjp")]
sig.GOcc=sig.GO[sig.GO$ontology=="CC",]
sig.GObp=sig.GO[sig.GO$ontology=="BP",]
sig.GOmf=sig.GO[sig.GO$ontology=="MF",]


GOslim.wall=goseq(pwf,"hg19","ensGene",gene2cat = go_slim2cat)
GOslim.wall$adjp=p.adjust(GOslim.wall$over_represented_pvalue,method="BH")
sig.slims=GOslim.wall[GOslim.wall$adjp<.05,c("category","term","numDEInCat","ontology","adjp")]
sig.slimscc=sig.slims[sig.slims$ontology=="CC",]
sig.slimsbp=sig.slims[sig.slims$ontology=="BP",]
sig.slimsmf=sig.slims[sig.slims$ontology=="MF",]



KEGG.wall=goseq(pwf,"hg19","ensGene",test.cats = "KEGG")
KEGG.wall$adjp=p.adjust(KEGG.wall$over_represented_pvalue,method="BH")
KEGGnames=(as.list(KEGGPATHID2NAME))
KEGG.wall$names=""
for(i in 1:nrow(KEGG.wall)){
  KEGG.wall$names[i]=KEGGnames[[KEGG.wall$category[i]]]
}
sig.KEGG=KEGG.wall[KEGG.wall$adjp<.05,c("names", "numDEInCat","adjp")]



```


```{r}

genesingo=as.list(org.Hs.egGO2ALLEGS)
ens2eg=as.list(org.Hs.egENSEMBL)
autoegs=as.character(genesingo[["GO:0006914"]])
autoens=unlist(ens2eg[autoegs])
autophagy.genes=(intersect(autoens,row.names(meancpm)))
sig.atg.genes=intersect(autophagy.genes, allsigs)

apopegs=as.character(genesingo[["GO:0006915"]])
apopens=unlist(ens2eg[apopegs])
apoptosis.genes=(intersect(apopens,row.names(meancpm)))
sig.apop.genes=intersect(apoptosis.genes, allsigs)

```


```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(FCdata[autophagy.genes,],scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Autophagy Genes",col=hmcolors, dendrogram = "row")

```

```{r fig.width=5,fig.height=5, fig.align="center"}
atg.hmd=heatmaply(FCdata[sig.atg.genes,],scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Autophagy Genes",col=hmcolors, dendrogram = "row")
atg.hmd
```


```{r}

order=atg.hmd$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],47,58))
order[,2]=as.numeric(substring(order[,2],47,58))
order[,3]=as.numeric(substring(order[,3],47,58))
order[,4]=as.numeric(substring(order[,4],47,58))
order[,5]=as.numeric(substring(order[,5],47,58))
order[,6]=as.numeric(substring(order[,6],47,58))


colnames(order)=colnames(FCdata)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]

order[setdiff(row.names(order),row.names(sCN2)),1]=NA
order[setdiff(row.names(order),row.names(sCN3)),2]=NA

order[setdiff(row.names(order),row.names(sCV2)),3]=NA
order[setdiff(row.names(order),row.names(sCV3)),4]=NA

order[setdiff(row.names(order),row.names(sEM2)),5]=NA
order[setdiff(row.names(order),row.names(sEM3)),6]=NA
atgorder=order
```





```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(atgorder,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Top 10% PC1 Contribution",col=hmcolors, dendrogram = "none")

```







```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(meancpm[apoptosis.genes,],scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Apoptosis Genes",col=hmcolors, dendrogram = "row")

```

```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(cpmdata[sig.apop.genes,],scale="row",trace="none",Colv = T,Rowv=T,cexRow = .1,main="Apoptosis Genes",col=hmcolors, dendrogram = "both")

```

```{r fig.width=5,fig.height=5, fig.align="center"}
apop.hmd=heatmaply(meancpm[sig.apop.genes,],scale="row",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Sig. Apoptosis Genes",col=hmcolors, dendrogram = "row")
apop.hmd
```

```{r}

order=apop.hmd$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],47,58))
order[,2]=as.numeric(substring(order[,2],47,58))
order[,3]=as.numeric(substring(order[,3],47,58))
order[,4]=as.numeric(substring(order[,4],47,58))
order[,5]=as.numeric(substring(order[,5],47,58))
order[,6]=as.numeric(substring(order[,6],47,58))
order[,7]=as.numeric(substring(order[,7],47,58))
order[,8]=as.numeric(substring(order[,8],47,58))
order[,9]=as.numeric(substring(order[,9],47,58))


colnames(order)=colnames(meancpm)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]
apoporder=order
```


```{r fig.width=5,fig.height=5, fig.align="center"}

heatmaply(apoporder[,1:3],scale="none",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Sig. Apoptosis Genes",col=hmcolors, dendrogram = "none")

```

```{r fig.width=5,fig.height=5, fig.align="center"}

heatmaply(apoporder[,4:6],scale="none",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Sig. Apoptosis Genes",col=hmcolors, dendrogram = "none")

```

```{r fig.width=5,fig.height=5, fig.align="center"}

heatmaply(apoporder[,7:9],scale="none",trace="none",Colv = F,Rowv=T,cexRow = .1,main="Sig. Apoptosis Genes",col=hmcolors, dendrogram = "none")

```

```{r}

order=apop.hmd$x$data[[1]][4]
ordernames=substring(order[[1]][,1],6,20)
order=order[[1]]
order[,1]=as.numeric(substring(order[,1],47,58))
order[,2]=as.numeric(substring(order[,2],47,58))
order[,3]=as.numeric(substring(order[,3],47,58))
order[,4]=as.numeric(substring(order[,4],47,58))
order[,5]=as.numeric(substring(order[,5],47,58))
order[,6]=as.numeric(substring(order[,6],47,58))
order[,7]=as.numeric(substring(order[,7],47,58))
order[,8]=as.numeric(substring(order[,8],47,58))
order[,9]=as.numeric(substring(order[,9],47,58))


colnames(order)=colnames(meancpm)
row.names(order)=ordernames
mode(order)="numeric"
order=order[nrow(order):1,]

order[setdiff(row.names(order),row.names(sCN2)),2]=NA
order[setdiff(row.names(order),row.names(sCN3)),3]=NA

order[setdiff(row.names(order),row.names(sCV2)),5]=NA
order[setdiff(row.names(order),row.names(sCV3)),6]=NA

order[setdiff(row.names(order),row.names(sEM2)),8]=NA
order[setdiff(row.names(order),row.names(sEM3)),9]=NA
apoporder=order
```





```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(apoporder,scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Sig. Apoptosis Genes",col=hmcolors, dendrogram = "none")

```


```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(apoporder[,4:6],scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Sig. Apoptosis Genes",col=hmcolors, dendrogram = "none")

```


```{r fig.width=5,fig.height=5, fig.align="center"}
heatmaply(apoporder[,7:9],scale="none",trace="none",Colv = F,Rowv=F,cexRow = .1,main="Sig. Apoptosis Genes",col=hmcolors, dendrogram = "none")

```

```{r}

cats=sig.GObp
slims=unlist(go)
gmt=matrix("",nrow=nrow(cats),ncol=(max(cats$numDEInCat)+2))
gmt[,1:2]=cats$term
i=1
while(i<=nrow(gmt)){
  gmt[i,3:(cats[i,"numDEInCat"]+2)]=intersect(substring(names(slims)[slims==cats[i,"category"]],1,15),row.names(hmd))
  i=i+1
}
write.csv(gmt,"/Users/johncsantiago/Documents/GitHub/SData/PC2_gobp.csv")

```




```{r}

scaled=(t(scale(t(tempmeancpm[row.names(order),]))))
hc <- hclust(dist(scaled), "complete")
dnd=as.dendrogram(hc,h=2)
plot(dnd)
cutree(dnd,h=2)

plot(as.dendrogram(hc))
abline(h=5.1,lty=2,col="red")

dnd=cut(as.dendrogram(hc),h=5.1)
plot(dnd$lower[[1]])


par(cex=0.7, mar=c(5, 8, 4, 1))
plot(hc, xlab="", ylab="", main="", sub="", axes=FALSE)
par(cex=1)
title(xlab="", ylab="", main="Violent crime rates by US state")
axis(2)
rect.hclust(hc,k=4, border = 3:4)


cats=sig.GObp$category
genesingomatrix=matrix(0,nrow=length(cats),ncol=length(sig.apop.genes))
row.names(genesingomatrix)=cats
colnames(genesingomatrix)=sig.apop.genes
i=1
while(i<=nrow(genesingomatrix)){
tempegs=as.character(genesingo[[row.names(genesingomatrix)[i]]])
tempens=unlist(ens2eg[tempegs])
temp.genes=(intersect(tempens,row.names(meancpm)))
sig.genes=intersect(temp.genes, colnames(genesingomatrix))
genesingomatrix[i,sig.genes]=1
i=i+1
}

adjacencymatrix=matrix(0,nrow=length(cats),ncol=length(cats))
row.names(adjacencymatrix)=cats
colnames(adjacencymatrix)=cats
allnames=unique()
i=1
j=3
rowgenes=colnames(genesingomatrix)[genesingomatrix[row.names(adjacencymatrix)[i],]==1]
colgenes=colnames(genesingomatrix)[genesingomatrix[row.names(adjacencymatrix)[j],]==1]

if(j<i){
  adjacencymatrix[i,j]=length(intersect(rowgenes,colgenes))/length(rowgenes)
}

if(j>i){
  adjacencymatrix[i,j]=length(intersect(rowgenes,colgenes))/length(colgenes)
}

if(j==i){
  adjacencymatrix[i,j]=length(intersect(rowgenes,colgenes))/length(colgenes)
}



```


```{r}

dataset=tempmeancpm[row.names(order),]
cutheight=4.4

scaled=(t(scale(t(dataset))))
row.names.scaled=ID.conversion[row.names(scaled),]
row.names.scaled[row.names.scaled[,2]=="",2]=row.names.scaled[row.names.scaled[,2]=="",1]
row.names(scaled)=row.names.scaled[,2]

colors=c("green3","gold3","royalblue","firebrick","black","violet","orange")

hc <- hclust(dist(scaled), "complete")
dnd=cut(as.dendrogram(hc),h=cutheight)

colordend=(color_branches(hc, h=cutheight, col=colors[1:length(dnd$lower)]))
heatmap.2(scaled[hc$order[length(hc$order):1],],trace="none",col=hmcolors,dendrogram = "row",Rowv=colordend,Colv="NA",cexRow = .1) ##,keysize = 1,lhei = c(1,5)) add this in console for better figure

```

```{r fig.height=4, fig.width=2.5}


par(cex=.3)
plot(colordend,horiz=T)
abline(v=cutheight, lty=2, col="red")
```



```{r}

clusternum=1

dnd=cut(as.dendrogram(hc),h=cutheight)

cluster=row.names(scaled)[unlist(dnd$lower[[clusternum]])]

clusterdend=color_branches(dnd$lower[[clusternum]], h=cutheight, col=colors[clusternum])
##colordend=(color_branches(hc, h=cutheight, col=colors[1:length(dnd$lower)]))

##heatmaply(scaled[cluster[length(cluster):1],],Rowv=F,Colv=F, dendrogram="none",col=hmcolors, cexRow=.7, main=paste("Genes in Cluster Number ", clusternum, sep=""))

heatmap.2(scaled,trace="none",col=hmcolors, dendrogram = "row", Rowv=clusterdend,Colv="NA",cexRow = .5,main=paste("Genes in Cluster Number ", clusternum, sep=""))

##heatmap.2(scaled[hc$order[length(hc$order):1],],trace="none",col=hmcolors,dendrogram = "row",Rowv=colordend,Colv="NA",cexRow = .1) 

```


```{r}
par(mar=c(4,1,8,1), cex=.7)
plot(clusterdend,horiz=T, cex=.7)

```